
stages:
  data_ingestion:
    cmd: python src/CNN_Classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CNN_Classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Brain_Tumor_Dataset


  prepare_base_model:
    cmd: python src/CNN_Classifier/pipeline/stage_02_base_model.py
    deps:
      - src/CNN_Classifier/pipeline/stage_02_base_model.py
      - config/config.yaml
    params:
      - input_shape
      - include_top
      - classes
      - weights
      - learning_rate
      - optimizer
      - loss
      - metrics
      - freeze_layers
      - l2_params
      - dropout
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/CNN_Classifier/pipeline/stage_03_training_model.py
    deps:
      - src/CNN_Classifier/pipeline/stage_03_training_model.py
      - src/CNN_Classifier/components/callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/Brain_Tumor_Dataset
      - artifacts/prepare_base_model
    params:
      - input_shape
      - epochs
      - batch_size
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  

  evaluation:
    cmd: python src/CNN_Classifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/CNN_Classifier/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Brain_Tumor_Dataset
      - artifacts/training/model.h5
    params:
      - input_shape
      - batch_size
    metrics:
    - scores.json:
        cache: false
